### ISSUE TITLE
Moving from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/arm64-assembly#4]
Hello 🙂 

Over the last few months we've been transferring all our CI from Travis to [GitHub Actions (GHA)](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions). We've found that GHA are easier to work with, more reliable, and much much faster. 

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and [shift everything to GHA](https://github.com/exercism/exercism/issues/5396). This issue acts as a call to action if your track is still using Travis. 

For most CI checks this should be a transposing from Travis' syntax to [GHA syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions), and hopefully quite straightforward (see [this PR for an example](https://github.com/exercism/csharp/pull/1338/files)).  However, if you do encounter any issues doing this, please ask on Slack where lots of us now have experience with GHA, or post a comment here and I'll tag relevant people. This would also make a good Hacktoberfest issue for anyone interested in making their first contribution 🙂 

If you've already switched this track to GHA, please feel free to close this issue and ignore it.

Thanks!

**Comment by ErikSchierboom** [comment]
We now have a really nice document and some starting workflows that you can use to help switch to GitHub Actions: https://github.com/exercism/problem-specifications/tree/master/workflows#workflow-templates

**Comment by ee7** [comment]
Note that this is less trivial for `arm64-assembly`, given that `travis.yml` contains:
https://github.com/exercism/arm64-assembly/blob/48b8e361f0f9af2be7b674f6779288610a3180ff/.travis.yml#L3-L4

and that GitHub Actions doesn't support `arm64` for its hosted environments (I believe it's possible to self-host).

I have verified that `arm64-assembly` and `nim` are the only v2 tracks that currently uses `arm64` on Travis.

**Comment by Chlorophytus** [comment]
I'm saving this in a comment, this seems to be a good start. I think it can be fixed up. When we fix it up I think we can enable this.

```yaml
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 # 2.4.0
      - uses: docker/setup-qemu-action@v1 # 1.2.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - run: bin/verify-exercises
```
